### ISSUE TITLE
Does this plugin work with craco-plugin-single-spa-application?

### ISSUE THREAD

**Issue by nicolerimando** [single-spa/standalone-single-spa-webpack-plugin#18]
I'm currently trying to convert a create-react-app to a MFE app using craco/craco-plugin-single-spa-application, but I haven't gotten the standalone plugin to work with it. Is it possible to get both working? Thanks!

**Comment by internettrans** [comment]
I imagine it would work but haven't tried this. This plugin interacts with html-webpack-plugin, which create-react-app uses.
